In [1]:
import pandas as pd
ventas_df = pd.read_csv("../data/ventas.csv" , sep =",")
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [2]:
ventas_df["region"] == "Sur"

0       False
1        True
2       False
3       False
4        True
        ...
1195    False
1196    False
1197    False
1198    False
1199    False
Name: region, Length: 1200, dtype: bool

In [4]:
ventas_df[ventas_df["region"] == "Sur"]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95,0.00
...,...,...,...,...,...,...,...,...
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [5]:
ventas_df[ventas_df["region"] == "Sur"].value_counts(subset="region")

region
Sur    240
Name: count, dtype: int64